use_frameworks!

platform :ios, '9.0'

target 'ODCustomFramework_Example' do
  pod 'ODCustomFramework', :path => '../'

  target 'ODCustomFramework_Tests' do
    inherit! :search_paths

    
  end
end
